removed controller routes and view related to register with email
geeksesi/code-review-pals pull request #38
Opened 2023-04-07 23:36 UTC by andreyyy178

2023-04-07 23:43 UTC, geeksesi requested changes
there is some Tests on : `tests/Feature/Auth` please delete them too.

2023-04-08 08:35 UTC, geeksesi approved these changes

2023-04-08 08:51 UTC, vassilidev commented
A lot of comment, remove the code

2023-04-08 08:52 UTC, vassilidev requested changes

2023-04-08 08:52 UTC, vassilidev commented on .github/workflows/laravel.yml
> +                      GNUTLS_CPUID_OVERRIDE=0x1 npm i
Why

2023-04-08 08:52 UTC, vassilidev commented on package.json
> +        "@fortawesome/free-brands-svg-icons": "^6.4.0",
Why

2023-04-08 08:52 UTC, vassilidev commented on resources/js/Pages/Welcome.jsx
> +                            {/*<Link*/}
Why

2023-04-08 08:52 UTC, vassilidev commented on routes/auth.php
>      Route::post('login', [AuthenticatedSessionController::class, 'store']);
Why

2023-04-08 08:52 UTC, vassilidev commented on routes/web.php
> +        //'canRegister' => Route::has('register'),
Why

2023-04-08 08:54 UTC, vassilidev commented
Hello,

I'm not gonna put all the changes u need to make but don't keep code if we don't use it, don't comment it.

You miss some files and change other.

Please review it.

2023-04-09 07:24 UTC, vassilidev commented
https://github.com/geeksesi/code-review-pals/pull/39

2023-04-09 07:24 UTC, closed without merging